---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - xytest.xy.io
  resources:
  - xydaemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xytest.xy.io
  resources:
  - xydaemonsets/finalizers
  verbs:
  - update
- apiGroups:
  - xytest.xy.io
  resources:
  - xydaemonsets/status
  verbs:
  - get
  - patch
  - update
