# This rule is not used by the project data itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to xytest.xy.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: data
    app.kubernetes.io/managed-by: kustomize
  name: xydaemonset-viewer-role
rules:
- apiGroups:
  - xytest.xy.io
  resources:
  - xydaemonsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - xytest.xy.io
  resources:
  - xydaemonsets/status
  verbs:
  - get
